package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.PathVariable;

import org.springframework.jdbc.core.JdbcTemplate;
import java.util.List;
import java.util.Map;
import java.lang.String;
import java.lang.Object;



@Controller // This means that this class is a Controller
@RequestMapping(path="/mascotas") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private MascotaRepository userRepository;

  @Autowired
  private JdbcTemplate jdbcTemplate;

  @PostMapping(path="/add") // Map ONLY POST Requests http://localhost:8080/demo/add
  public @ResponseBody String addNewUser (@RequestParam String nombre, @RequestParam String raza, @RequestParam String propietario) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Mascota n = new Mascota();
    n.setNombre(nombre);
    n.setRaza(raza);
    n.setPropietario(propietario);

    userRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")     // http://localhost:8080/demo/all
  public @ResponseBody Iterable<Mascota> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }

  @PutMapping(path="/edit")
  public @ResponseBody String editUser(@RequestParam Integer id, @RequestParam String nombre, @RequestParam String raza, @RequestParam String propietario) {
    Mascota n = new Mascota();
    n.setId(id);
    n.setNombre(nombre);
    n.setRaza(raza);
    n.setPropietario(propietario);
    userRepository.save(n);
    return "Updated";
  }

  @GetMapping(path="/ver/{id}")
  public @ResponseBody Mascota getOneUser(@PathVariable Integer id) {
    return userRepository.findById(id).orElse(null);
  }

  @DeleteMapping(path="/del")
  public @ResponseBody String deleteUser(@RequestParam Integer id) {
    Mascota n = new Mascota();
    n.setId(id);
    userRepository.delete(n);
    return "Deleted";
  }

  @GetMapping(path="/get/report")
  public @ResponseBody List reporte() {
    String sql = "SELECT CONCAT(nombre, ' ==> ', raza) as mycol FROM mascota";
    List<Map<String, Object>> results = jdbcTemplate.queryForList(sql);
    return results;
  }





}